# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6638f3374758de0dce996fc8f45535993c0368ef9b0363fc8d2e44ece28ffe11077d2a72ba0829a1359ec9d581576a6b559add66f8d533a32f7fcc403c9a914

test:
  secret_key_base: dfe55c560ac58154ad41ee5fb2919558f7fae22a7ae38179f52e0b6df591ffb3ede2ab298d4f3487a01293bd0fca5572612a12edfeb4aa4d0f8068998ba2a033

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
